# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zA6cf_U_tNDKITldc4WZnHsvajQ3TU-Y
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
             'i love my cat',
             'i hate my donkey',
             'my dog ran away to play with another dog'
]
tokenizer = Tokenizer(num_words = 100, oov_token="<unk>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

sequence = tokenizer.texts_to_sequences(sentences)
print(sequence)

sne = ['hello how are you']
tokenizer.texts_to_sequences(sne)

# from google.colab import drive
# drive.mount('/content/drive')

padded = pad_sequences(sequence, padding = 'post', truncating = 'post', maxlen =7)
print(padded)

test = ['my dog loves my cat',
        'i hate my manate ']
test_pad = pad_sequences(tokenizer.texts_to_sequences(test),padding = 'post', truncating='post', maxlen = 7)

test_pad

import json

with open('Sarcasm_Headlines_Dataset.json','r') as f:
  datast = json.load(f)

